version: "3.7"

services:
  app:
    environment:
      DISPLAY_COUNTER: 'false'
      MENU: >-
        [
          ["Home", "/"]
        ]
    image: gabe565/0bin
    build: .
    restart: unless-stopped
    volumes:
      - data:/data
      - ./views:/app/zerobin/views:ro

volumes:
  data:
